name: Deploy Terraform to AWS

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      destroy:
        description: "Destroy infrastructure?"
        required: false
        default: "false"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest ./app

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: project
        run: terraform init
        env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_DEFAULT_REGION: us-east-1

      - name: Terraform Plan
        if: ${{ github.event.inputs.destroy != 'true' }}
        working-directory: project
        run: terraform plan -out=tfplan
        env:
          TF_VAR_docker_image: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        if: ${{ github.event.inputs.destroy != 'true' }}
        working-directory: project
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_docker_image: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Destroy
        if: ${{ github.event.inputs.destroy == 'true' }}
        working-directory: project
        run: terraform destroy -auto-approve
        env:
          TF_VAR_docker_image: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
